export const ADD_POSTER_STARTED = 'ADD_POSTER_STARTED';
export const ADD_POSTER_SUCCESS = 'ADD_POSTER_SUCCESS';
export const ADD_POSTER_FAILURE = 'ADD_POSTER_FAILURE';

export const UPDATE_POSTER_STARTED = 'UPDATE_POSTER_STARTED';
export const UPDATE_POSTER_SUCCESS = 'UPDATE_POSTER_SUCCESS';
export const UPDATE_POSTER_FAILURE = 'UPDATE_POSTER_FAILURE';

export const DELETE_POSTER_STARTED = 'DELETE_POSTER_STARTED';
export const DELETE_POSTER_SUCCESS = 'DELETE_POSTER_SUCCESS';
export const DELETE_POSTER_FAILURE = 'DELETE_POSTER_FAILURE';

export const GET_POSTERS_STARTED = 'GET_POSTERS_STARTED';
export const GET_POSTERS_SUCCESS = 'GET_POSTERS_SUCCESS';
export const GET_POSTERS_FAILURE = 'GET_POSTERS_FAILURE';

export const GET_POSTERS_BY_CATEGORY_STARTED = 'GET_POSTERS_BY_CATEGORY_STARTED';
export const GET_POSTERS_BY_CATEGORY_SUCCESS = 'GET_POSTERS_BY_CATEGORY_SUCCESS';
export const GET_POSTERS_BY_CATEGORY_FAILURE = 'GET_POSTERS_BY_CATEGORY_FAILURE';

export const GET_POSTERS_BY_SEARCH_STARTED = 'GET_POSTERS_BY_CATEGORY_STARTED';
export const GET_POSTERS_BY_SEARCH_SUCCESS = 'GET_POSTERS_BY_CATEGORY_SUCCESS';
export const GET_POSTERS_BY_SEARCH_FAILURE = 'GET_POSTERS_BY_CATEGORY_FAILURE';

export const GET_POSTER_BY_ID_STARTED = 'GET_POSTER_BY_ID_STARTED';
export const GET_POSTER_BY_ID_SUCCESS = 'GET_POSTER_BY_ID_SUCCESS';
export const GET_POSTER_BY_ID_FOR_POSTER_INFO_SUCCESS = 'GET_POSTER_BY_ID_FOR_POSTER_INFO_SUCCESS';
export const GET_POSTER_BY_ID_FAILURE = 'GET_POSTER_BY_ID_FAILURE';

export const GET_POSTERS_TOTAL_AMOUNT = 'GET_POSTERS_TOTAL_AMOUNT';
export const GET_POSTERS_BY_CATEGORY_TOTAL_AMOUNT = 'GET_POSTERS_BY_CATEGORY_TOTAL_AMOUNT';
export const GET_POSTERS_BY_SEARCH_TOTAL_AMOUNT = 'GET_POSTERS_BY_CATEGORY_TOTAL_AMOUNT';

export const GET_SELECTED_POSTER = 'GET_SELECTED_POSTER';
export const SET_SELECTED_POSTER = 'SET_SELECTED_POSTER';

export const SET_POSTER_DATA_FROM_FORM = 'SET_POSTER_DATA_FROM_FORM';

export const SET_ACTIVE_NAV = 'SET_ACTIVE_NAV';
export const GET_ACTIVE_NAV = 'GET_ACTIVE_NAV';

export const SET_VARIANT_SORT = 'SET_VARIANT_SORT';
export const GET_VARIANT_SORT = 'GET_VARIANT_SORT';

export const CLOSE_FORMS = 'CLOSE_FORMS';
export const OPEN_MODAL_FORM = 'OPEN_MODAL_FORM';
